### ISSUE TITLE
Duplicate expression entries on glycan page

### ISSUE THREAD

**Issue by kmartinez834** [glygener/glygen-issues#1269]
All of the P07288-1 Asn69 rows appear to be identical:
https://www.glygen.org/glycan/G59655SA#Expression
![image](https://github.com/glygener/glygen-issues/assets/90285371/c0eee68c-a7e6-43a6-a1d9-a46567b0a488)

However, the API includes abundance information, so these are separate objects.  Add abundance to glycan details page or remove redundant rows from expression section?
``` json
"expression": [
    {
      "category": "tissue",
      "tissue": {
        "name": "seminal fluid",
        "namespace": "UBERON",
        "id": "0006530",
        "url": "http://purl.obolibrary.org/obo/UBERON_0006530"
      },
      "abundance": "15.36%",
      "evidence": [
        {
          "id": "33167210",
          "database": "PubMed",
          "url": "https://glygen.org/publication/PubMed/33167210"
        },
        {
          "id": "10.1016/j.talanta.2020.121495",
          "database": "DOI",
          "url": "https://glygen.org/publication/DOI/10.1016/j.talanta.2020.121495"
        }
      ],
      "start_pos": 69,
      "end_pos": 69,
      "residue": "Asn",
      "uniprot_canonical_ac": "P07288-1"
    },
    {
      "category": "tissue",
      "tissue": {
        "name": "seminal fluid",
        "namespace": "UBERON",
        "id": "0006530",
        "url": "http://purl.obolibrary.org/obo/UBERON_0006530"
      },
      "abundance": "17.01%",
      "evidence": [
        {
          "id": "33167210",
          "database": "PubMed",
          "url": "https://glygen.org/publication/PubMed/33167210"
        },
        {
          "id": "10.1016/j.talanta.2020.121495",
          "database": "DOI",
          "url": "https://glygen.org/publication/DOI/10.1016/j.talanta.2020.121495"
        }
      ],
      "start_pos": 69,
      "end_pos": 69,
      "residue": "Asn",
      "uniprot_canonical_ac": "P07288-1"
    },
```

**Comment by kmartinez834** [comment]
We discussed during the General meeting today.  We want to add a column to the Glycan details expression section with an icon that enables user to select publication with abundance info. 

Need to decide if this will be implemented by front end or back end.

**Comment by ReneRanzinger** [comment]
@sujeetvkulkarni Is this information client or server side paginated?

**Comment by sujeetvkulkarni** [comment]
@ReneRanzinger Both expression table entries (tissue and cell line) are server side paginated.

**Comment by ReneRanzinger** [comment]
In that case the duplication needs to happen server side. To be able to make the icon we will have to add new properties in the JSON:
* Does it have evidence data?
* Which papers have evidence data?

**Comment by sujeetvkulkarni** [comment]
@ReneRanzinger @rykahsay A property with paper list, having evidence data will be good. As we can display list of paper ids (with links to publication details page) in the Abundance column. Array can be empty if there is no abundance data.

```
abundance: [
       {
          "id": "33167210",
          "database": "PubMed",
          "url": "https://glygen.org/publication/PubMed/33167210"
        },
        {
          "id": "10.1016/j.talanta.2020.121495",
          "database": "DOI",
          "url": "https://glygen.org/publication/DOI/10.1016/j.talanta.2020.121495"
        }
      ]
```

**Comment by rykahsay** [comment]
Am I missing something? Why a simple addition of "abundance" column to the table in the frontend cannot address this? Why do we need to change the data model?

**Comment by sujeetvkulkarni** [comment]
@rykahsay abundance data is associated with a paper/evidence and should not be added directly at row level but a link should be provided to the user pointing him to the paper was the idea. Also, duplicate entries need to removed like explained above. @ReneRanzinger please comment.

**Comment by sujeetvkulkarni** [comment]
@rykahsay will remove duplicate entries from "expression": [] from glycan details response by removing abundance values from the object.

**Comment by rykahsay** [comment]
I have fixed it and here is the "expression" section coming from the API. I don't know why the frontend keeps saying 6 results (screenshot given below) while the API is giving only 3 objects

```
"expression": [
        {
            "category": "tissue",
            "end_pos": 69,
            "evidence": [
                {
                    "database": "PubMed",
                    "id": "33167210",
                    "url": "https://glygen.org/publication/PubMed/33167210"
                },
                {
                    "database": "DOI",
                    "id": "10.1016/j.talanta.2020.121495",
                    "url": "https://glygen.org/publication/DOI/10.1016/j.talanta.2020.121495"
                }
            ],
            "residue": "Asn",
            "start_pos": 69,
            "tissue": {
                "id": "0006530",
                "name": "seminal fluid",
                "namespace": "UBERON",
                "url": "http://purl.obolibrary.org/obo/UBERON_0006530"
            },
            "uniprot_canonical_ac": "P07288-1"
        },
        {
            "category": "tissue",
            "evidence": [
                {
                    "database": "GlyConnect",
                    "id": "1062",
                    "url": "https://glyconnect.expasy.org/browser/structures/1062"
                },
                {
                    "database": "GlyConnect",
                    "id": "620",
                    "url": "https://glyconnect.expasy.org/browser/proteins/620"
                },
                {
                    "database": "PubMed",
                    "id": "8130392",
                    "url": "https://glygen.org/publication/PubMed/8130392"
                }
            ],
            "tissue": {
                "id": "0002113",
                "name": "kidney",
                "namespace": "UBERON",
                "url": "http://purl.obolibrary.org/obo/UBERON_0002113"
            },
            "uniprot_canonical_ac": "P04070-1"
        },
        {
            "category": "tissue",
            "evidence": [
                {
                    "database": "GlyConnect",
                    "id": "1062",
                    "url": "https://glyconnect.expasy.org/browser/structures/1062"
                },
                {
                    "database": "GlyConnect",
                    "id": "952",
                    "url": "https://glyconnect.expasy.org/browser/proteins/952"
                },
                {
                    "database": "PubMed",
                    "id": "1668529",
                    "url": "https://glygen.org/publication/PubMed/1668529"
                }
            ],
            "tissue": {
                "id": "0002048",
                "name": "lung",
                "namespace": "UBERON",
                "url": "http://purl.obolibrary.org/obo/UBERON_0002048"
            }
        }
    ]
```

<img width="1324" alt="image" src="https://github.com/glygener/glygen-issues/assets/20584876/eb416801-98b8-44e5-a9d6-50fd994861c6">

**Comment by sujeetvkulkarni** [comment]
looks fine to me. @kmartinez834 please verify.

**Comment by kmartinez834** [comment]
Reassigning to @Luke-Johnson-5 , let me know if you have questions

**Comment by Luke-Johnson-5** [comment]
@sujeetvkulkarni Still seeing the issue that @rykahsay described above. Only three objects in the JSON, see below, but the site is showing 1 to 6 of 6 on https://tst.glygen.org/glycan/G59655SA#Expression

![image](https://github.com/glygener/glygen-issues/assets/144174552/fe143972-e8f8-4816-83b3-4b3be9d62298)


```javascript
 "expression": [
    {
      "category": "tissue",
      "tissue": {
        "name": "seminal fluid",
        "namespace": "UBERON",
        "id": "0006530",
        "url": "http://purl.obolibrary.org/obo/UBERON_0006530"
      },
      "evidence": [
        {
          "id": "33167210",
          "database": "PubMed",
          "url": "https://glygen.org/publication/PubMed/33167210"
        },
        {
          "id": "10.1016/j.talanta.2020.121495",
          "database": "DOI",
          "url": "https://glygen.org/publication/DOI/10.1016/j.talanta.2020.121495"
        }
      ],
      "start_pos": 69,
      "end_pos": 69,
      "residue": "Asn",
      "uniprot_canonical_ac": "P07288-1"
    },
    {
      "category": "tissue",
      "tissue": {
        "name": "kidney",
        "namespace": "UBERON",
        "id": "0002113",
        "url": "http://purl.obolibrary.org/obo/UBERON_0002113"
      },
      "evidence": [
        {
          "id": "1062",
          "database": "GlyConnect",
          "url": "https://glyconnect.expasy.org/browser/structures/1062"
        },
        {
          "id": "620",
          "database": "GlyConnect",
          "url": "https://glyconnect.expasy.org/browser/proteins/620"
        },
        {
          "id": "8130392",
          "database": "PubMed",
          "url": "https://glygen.org/publication/PubMed/8130392"
        }
      ],
      "uniprot_canonical_ac": "P04070-1"
    },
    {
      "category": "tissue",
      "tissue": {
        "name": "lung",
        "namespace": "UBERON",
        "id": "0002048",
        "url": "http://purl.obolibrary.org/obo/UBERON_0002048"
      },
      "evidence": [
        {
          "id": "1062",
          "database": "GlyConnect",
          "url": "https://glyconnect.expasy.org/browser/structures/1062"
        },
        {
          "id": "952",
          "database": "GlyConnect",
          "url": "https://glyconnect.expasy.org/browser/proteins/952"
        },
        {
          "id": "1668529",
          "database": "PubMed",
          "url": "https://glygen.org/publication/PubMed/1668529"
        }
      ]
    }
  ],
```

**Comment by sujeetvkulkarni** [comment]
@Luke-Johnson-5 thanks for pointing this out, this is an api issue. @rykahsay you will need update section stats info for the expression tables (expression, expression_tissue, expression_cell_line) according to new logic on glycan details api response.

![Screenshot 2024-05-22 at 1 01 00 PM](https://github.com/glygener/glygen-issues/assets/13891482/4b76b840-f693-4a85-90b0-5c9a28222321)

**Comment by rykahsay** [comment]
Fixed on tst:

<img width="1391" alt="image" src="https://github.com/glygener/glygen-issues/assets/20584876/c943d2f6-d257-47f9-89bc-e84e92055f75">

**Comment by Luke-Johnson-5** [comment]
Can confirm looks good.
