### ISSUE TITLE
Push BCOs to https://data.tst.glygen.org/

### ISSUE THREAD

**Issue by kmartinez834** [glygener/glygen-issues#1351]
All BCOs have been created and reviewed.  Push to TST.

**Comment by rykahsay** [comment]
I still see some issues:

$ python3 check-bco2filename-mapping.py  | grep ERROR
NO-BCO,chicken_proteoform_glycosylation_sites_literature.csv,ERROR,in_fs
NO-BCO,chicken_proteoform_glycosylation_sites_unicarbkb.csv,ERROR,in_fs

**Comment by rykahsay** [comment]
Done

**Comment by kmartinez834** [comment]
- The following URLs are crashing when I try to open them:
https://data.tst.glygen.org/GLY_001025
https://data.tst.glygen.org/GLY_001015
--> I believe this is because there is no "usability_domain" array.  I have added this to the drafts, please patch these new BCOs.

- The pipeline steps and execution domain script uri for the ML ready datasets (GLY_001045 and GLY_001046) were programatically updated, however these need to point to my personal github (ex. changed from `https://github.com/kmartinez834/Masters-Thesis/raw/main/ccRCC/human_proteoform_ml_ready_pdc_ccrc.csv` to `https://github.com/kmartinez834/Masters-Thesis/raw/v-x.x.x/ccRCC/human_proteoform_ml_ready_pdc_ccrc.csv`)
--> If you would prefer to keep the files within the glygen github and server, let me know and I will provide the scripts

- GLY_000979 was created for chicken_proteoform_glycosylation_sites_literature.csv, however the IO output is human_proteoform_glycosylation_sites_literature.csv.  This chicken dataset was removed from the dataset-masterlist.json because the file is empty.  I have removed the contents of the IO domain, deleted the name and changed status to Retired.
--> Update data.tst.glygen.org so that GLY_000979 does not appear

- GLY_000964: The name of this BCO was changed to "null" because it was a duplicate of GLY_000906, however the IO output was not deleted and status was not changed to retired.  I have fixed this.
--> Push changes so that GLY_000906 appears on data.tst.glygen.org and not GLY_000964

**Comment by rykahsay** [comment]
@kmartinez834  ... please make separate tickets for each issues. It is very difficult to track when you have multiple issues on a thread. 

In this ticket, I expect people to comment ONLY on "what they have looked tested"

**Comment by rykahsay** [comment]
I don't like it when you place many issues in one ticket .... please let's avoid this in the future.

[GLY_001025

https://data.tst.glygen.org/GLY_001025 and https://data.tst.glygen.org/GLY_001015 are loading now ... but actual rows are still loading to MongoDB (will be available in few hours)

GLY_000979 has been removed


GLY_000964: The name of this BCO was changed to "null" because it was a duplicate of GLY_000906, however the IO output was not deleted and status was not changed to retired. I have fixed this.
--> Push changes so that GLY_000906 appears on data.tst.glygen.org and not GLY_000964




The pipeline steps and execution domain script uri for the ML ready datasets (GLY_001045 and GLY_001046)  ...

>>> I don't like the idea having reference to "personal" github account ... why don't you create a repo within the GlyGen organization space and put the code there

**Comment by kmartinez834** [comment]
The above changes have still not populated on data.tst.glygen.org

**Comment by rykahsay** [comment]
### Loading GLY_001025
<img width="1322" alt="image" src="https://github.com/glygener/glygen-issues/assets/20584876/36dc7be7-b4b8-495f-a1b7-3dc6ee5ea00b">

### Loading GLY_001015
<img width="618" alt="image" src="https://github.com/glygener/glygen-issues/assets/20584876/b68d532a-37b7-4895-95c0-d6325281d3d6">

### Loading GLY_000906
<img width="800" alt="image" src="https://github.com/glygener/glygen-issues/assets/20584876/9281f7dc-eca9-457c-99f7-bf016ae9a88a">


### Removed GLY_000979
<img width="993" alt="image" src="https://github.com/glygener/glygen-issues/assets/20584876/fca6cec1-e6ef-43a7-800b-100e265e216b">

### Removed GLY_000964
<img width="929" alt="image" src="https://github.com/glygener/glygen-issues/assets/20584876/ad28f301-3dc7-4c54-bbec-c2bacc73c725">

**Comment by kmartinez834** [comment]
Made additional updates to GLY_001015, GLY_001045 and GLY_001046, please patch these BCOs

**Comment by kmartinez834** [comment]
How much work is it to just push all of them again?  I just found and correctly 100 other usability domains with outdated information.

**Comment by rykahsay** [comment]
Check tst now and let me know if it looks ok -- then I will push to prd

**Comment by kmartinez834** [comment]
Just these two issues:

- I retired GLY_001036 but it's still showing up:
https://data.tst.glygen.org/GLY_001036
![image](https://github.com/glygener/glygen-issues/assets/90285371/eac39983-ea83-4d3c-878b-aa9a6800ad8a)

- GLY_000976 was retired and should result in a "no record found" error, but I'm getting the loading symbol:
https://data.tst.glygen.org/GLY_000976
![image](https://github.com/glygener/glygen-issues/assets/90285371/42966ace-c1e3-434d-aecc-60e60b31d0e6)

**Comment by rykahsay** [comment]
Check now:

<img width="965" alt="image" src="https://github.com/glygener/glygen-issues/assets/20584876/d4c03de6-4498-4d32-aaae-90f78343836e">

<img width="952" alt="image" src="https://github.com/glygener/glygen-issues/assets/20584876/d70b124e-c749-44ac-b8b6-7b4be9d93e2b">

**Comment by kmartinez834** [comment]
Please push to PRD

**Comment by rykahsay** [comment]
Done, please check
