### ISSUE TITLE
Event banner comes up early and stops showing early than scheduled start and end date

### ISSUE THREAD

**Issue by sujeetvkulkarni** [glygener/glygen-issues#651]
When I created event banner on prod and beta it looks like they come and go early than scheduled time as per Eastern Standard Time . Event banner should follow Eastern Standard Time.

API : https://api.glygen.org/event/addnew

```
{
  "title": "some title",
  "description": "some description",
  "start_date": "01/20/2021 23:59:59",
  "end_date": "01/21/2021 07:00:00",
  "venue": "some venue",
  "url": "some url",
  "url_name": "some url name",
  "visibility": "visible"
}
```

start_date and end date should be in EST.

I tried to create an event on tst server but it failed authentication with myglygen@gmail.com. #650

**Comment by rykahsay** [comment]
I have fixed it on tst, will be pushed when we push to prd for 2.2

### query that returns current/unexpired events
```
query:
{
   "visibility":"all", 
   "status":"current"
}


response:
[
    {
        "createdts": "2023-09-02 16:15:49 ",
        "description": "some description",
        "end_date": "2023-09-02 12:20:00 ",
        "end_date_s": 63821650800,
        "id": "64f35fb5e93dd2dc0f0964aa",
        "start_date": "2023-09-02 12:00:00 ",
        "start_date_s": 63821649600,
        "title": "some title",
        "updatedts": "2023-09-02 16:15:49 ",
        "url": "some url",
        "url_name": "some url name",
        "venue": "some venue",
        "visibility": "visible"
    }
]
```


### query that returns all events
```
query:
{
   "visibility":"all", 
   "status":"all"
}

response:
[
    {
        "createdts": "2023-09-02 16:15:49 ",
        "description": "some description",
        "end_date": "2023-09-02 12:20:00 ",
        "end_date_s": 63821650800,
        "id": "64f35fb5e93dd2dc0f0964aa",
        "start_date": "2023-09-02 12:00:00 ",
        "start_date_s": 63821649600,
        "title": "some title",
        "updatedts": "2023-09-02 16:15:49 ",
        "url": "some url",
        "url_name": "some url name",
        "venue": "some venue",
        "visibility": "visible"
    },
    {
        "createdts": "2023-09-01 19:49:09 ",
        "description": "some description",
        "end_date": "2023-09-01 15:50:00 ",
        "end_date_s": 63821577000,
        "id": "64f24035e93dd2dc0f09463a",
        "start_date": "2023-09-01 14:15:00 ",
        "start_date_s": 63821571300,
        "title": "some title",
        "updatedts": "2023-09-01 19:49:09 ",
        "url": "some url",
        "url_name": "some url name",
        "venue": "some venue",
        "visibility": "visible"
    },
...
]
```

**Comment by sujeetvkulkarni** [comment]
On tst if try to login using login api from http://localhost:3000/ I am getting strict origin error.
So can't add event or video.

Request URL:
https://api.tst.glygen.org/auth/login
Referrer Policy:
strict-origin-when-cross-origin

**Comment by rykahsay** [comment]
I tried it on tst and the problem should be gone, please close this ticket

**Comment by sujeetvkulkarni** [comment]
test on beta and prod when deployed.

**Comment by sujeetvkulkarni** [comment]
looks like the issue is still there on beta
created a banner to start at 1 pm (13:00:00) but it started to show around 12:10 pm EST.

```
 {
    "title": "GlyGen Webinar with Dr. Marissa Maciej-Hulme",
    "description": "Pushing new frontiers in GAGomics",
    "start_date": "2023-09-25 13:00:00 ",
    "end_date": "2023-09-26 11:59:00 ",
    "url": "https://wiki.glygen.org/GlyGen_Webinar_Series",
    "url_name": "More Information",
    "visibility": "visible",
    "start_date_s": 63823640400,
    "end_date_s": 63823723140,
    "createdts": "2023-09-25 16:08:32 ",
    "updatedts": "2023-09-25 16:08:32 ",
    "id": "6511b080305b94d21dbc9373"
  },
```

**Comment by sujeetvkulkarni** [comment]
Also the banner went away earlier than expected.

**Comment by rykahsay** [comment]
Can you please show me the query you are submitting when you call the event/list API?

**Comment by sujeetvkulkarni** [comment]
To add new event below API call was made.

```
				var svcUrl1 = "https://beta-api.glygen.org/event/addnew";
				
				var reqObj1 = {
					"title": "GlyGen Webinar with Dr. Marissa Maciej-Hulme",
					"description": "Pushing new frontiers in GAGomics",
					"start_date": "09/25/2023 13:00:00",
					"end_date": "09/26/2023 11:59:00",
					"url": "https://wiki.glygen.org/GlyGen_Webinar_Series",
					"url_name": "More Information",
					"visibility": "visible"
					};

				const requestOptions1 = {
				method: 'POST',
				headers: { 'Content-Type': 'application/json', 'X-CSRF-TOKEN': js.access_csrf, 'Authorization': 'Bearer ' +  js.access_token},
				body: JSON.stringify(reqObj1),
				credentials: 'include'
				};
				fetch(svcUrl1, requestOptions1).then((res) => res.json().then(re => {
					console.log(re);
				}))
```

To list events I called
https://beta-api.glygen.org/event/list/
on swagger (https://beta-api.glygen.org/) with 
{
  "visibility": "all",
  "status": "all"
}

default vaules.

**Comment by rykahsay** [comment]
No, you have to use "status": "current" because you are interested on events that are not expired.

**Comment by sujeetvkulkarni** [comment]
> No, you have to use "status": "current" because you are interested on events that are not expired.

Oh, I was talking about how I retrieved information shown in above example. In the frontend event information comes from
https://api.tst.glygen.org/pages/home_init API.

```
  "events": [
    {
      "title": "TEST EVENT",
      "description": "some description",
      "start_date": "2023-09-28 12:30:00 ",
      "end_date": "2023-09-29 11:30:00 ",
      "venue": "some venue",
      "url": "some url",
      "url_name": "some url name",
      "visibility": "visible",
      "start_date_s": 63823897800,
      "end_date_s": 63823980600,
      "createdts": "2023-09-28 15:49:28 ",
      "updatedts": "2023-09-28 15:49:28 ",
      "id": "6515a088a58e67d48175e2e7"
    }
  ],

```

**Comment by rykahsay** [comment]
I have modified home_init, it gives you "status"="current" events only. 

<img width="581" alt="image" src="https://github.com/glygener/glygen-issues/assets/20584876/2819b165-b0db-46ee-83fe-7cce8b5483b7">

**Comment by sujeetvkulkarni** [comment]
@rykahsay 
is this fixed on beta?

I created event on beta on 10:54 am and wanted to start it at 12:05:00 but the event started immediately.  home_init api stated sending is sending the event immediately, instead of from 12:05:00.

 {
    "title": "TEST EVENT 1",
    "description": "some description",
    "start_date": "2023-09-29 12:05:00 ",
    "end_date": "2023-09-29 16:30:00 ",
    "url": "https://wiki.glygen.org/GlyGen_Webinar_Series",
    "url_name": "More Information",
    "visibility": "visible",
    "start_date_s": 63823982700,
    "end_date_s": 63823998600,
    "createdts": "2023-09-29 14:54:20 ",
    "updatedts": "2023-09-29 14:54:20 ",
    "id": "6516e51c305b94d21dbca55f"
  },

**Comment by rykahsay** [comment]
Oh ... there was a problem with it, I have fixed it on both tst and beta now.

**Comment by sujeetvkulkarni** [comment]
On beta earlier 2 events TEST EVENT and TEST EVENT 1 were getting shown. Now both stopped showing. home_init not returning both.

 TEST EVENT 1 - should start on 12:05 so I will wait and check but beta should have shown TEST EVENT, which falls within time range. But beta is not showing  "TEST EVENT" too. please check.

    "start_date": "2023-09-28 15:30:00 ",
    "end_date": "2023-09-29 15:30:00 ",

```
  {
    "title": "TEST EVENT",
    "description": "some description",
    "start_date": "2023-09-28 15:30:00 ",
    "end_date": "2023-09-29 15:30:00 ",
    "venue": "some venue",
    "url": "some url",
    "url_name": "some url name",
    "visibility": "visible",
    "start_date_s": 63823908600,
    "end_date_s": 63823995000,
    "createdts": "2023-09-28 19:52:52 ",
    "updatedts": "2023-09-28 19:52:52 ",
    "id": "6515d994305b94d21dbca351",
    "now_ts": 63823979758
  },
```

**Comment by rykahsay** [comment]
Two are showing now

```
[
    {
        "title": "TEST EVENT 1",
        "description": "some description",
        "start_date": "2023-09-29 12:05:00 ",
        "end_date": "2023-09-29 16:30:00 ",
        "url": "https://wiki.glygen.org/GlyGen_Webinar_Series",
        "url_name": "More Information",
        "visibility": "visible",
        "start_date_s":        63823982700,
        "now_in_seconds": 63823984221
        "end_date_s":         63823998600,
        "createdts": "2023-09-29 14:54:20 ",
        "updatedts": "2023-09-29 14:54:20 ",
        "id": "6516e51c305b94d21dbca55f"
    },
    {
        "title": "TEST EVENT",
        "description": "some description",
        "start_date": "2023-09-28 15:30:00 ",
        "end_date": "2023-09-29 15:30:00 ",
        "venue": "some venue",
        "url": "some url",
        "url_name": "some url name",
        "visibility": "visible",
        "start_date_s":        63823908600,
        "now_in_seconds": 63823984221
        "end_date_s":         63823995000,
        "createdts": "2023-09-28 19:52:52 ",
        "updatedts": "2023-09-28 19:52:52 ",
        "id": "6515d994305b94d21dbca351"
    }
]
```

**Comment by sujeetvkulkarni** [comment]
@rykahsay looks good on beta. I will check if event will stop showing on beta.
I had created similar even on tst server using your scripts but I guess these changes are missing on tst server as the event is not getting shown there.
